### ISSUE TITLE
Login problems with checkworker method in the main

### ISSUE THREAD

**Issue by ZDevelop94** [ZDevelop94/GUIWarehouse3#27]
the checkworker method only checks the username and doesn't confirm the password. 
For example:
John
hasgdfhgashgf 
would be accepted where this should be incorrect. 
i would do it but I don't want to clash with someone else changing the main as i am focusing on the GUI. Thanks.

**Comment by thelemens** [comment]
Im on it

**Comment by thelemens** [comment]
Done.
